// Generated by CoffeeScript 1.4.0
var DashboardCollection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DashboardCollection = (function(_super) {

  __extends(DashboardCollection, _super);

  function DashboardCollection() {
    return DashboardCollection.__super__.constructor.apply(this, arguments);
  }

  DashboardCollection.prototype.model = Dashboard;

  DashboardCollection.prototype.url = '/result';

  DashboardCollection.prototype.db = {
    view: "resultsByQuestionAndComplete"
  };

  DashboardCollection.prototype.fetch = function(options) {
    if (options == null) {
      options = {};
    }
    if (options.include_docs == null) {
      options.include_docs = true;
    }
    if (options != null ? options.question : void 0) {
      options.descending = "true";
      if (options.isComplete != null) {
        options.startkey = options.question + ":" + options.isComplete + ":z";
        options.endkey = options.question + ":" + options.isComplete;
      } else {
        options.startkey = options.question + ":z";
        options.endkey = options.question;
      }
    }
    return DashboardCollection.__super__.fetch.call(this, options);
  };

  DashboardCollection.prototype.notSent = function() {
    return this.filter(function(result) {
      var _ref;
      return !((_ref = result.get("sentTo")) != null ? _ref.length : void 0);
    });
  };

  DashboardCollection.prototype.filteredByQuestionCategorizedByStatus = function(questionType) {
    var returnObject;
    returnObject = {};
    returnObject.complete = [];
    returnObject.notCompete = [];
    this.each(function(result) {
      if (result.get("question") !== questionType) {
        return;
      }
      switch (result.get("complete")) {
        case true:
          return returnObject.complete.push(result);
        default:
          return returnObject.notComplete.push(result);
      }
    });
    return returnObject;
  };

  DashboardCollection.prototype.filterByQuestionType = function(questionType) {
    return this.filter(function(result) {
      return result.get("question") === questionType;
    });
  };

  DashboardCollection.prototype.partialResults = function(questionType) {
    return this.filter(function(result) {
      return result.get("question") === questionType && !result.complete();
    });
  };

  return DashboardCollection;

})(Backbone.Collection);
